

/* USER 테이블 인서트 */
INSERT INTO triple.USER(USER_ID, NAME,  RGST_DTM, RGST_ID) VALUES(UUID(), '장기하', NOW(),  '0');
INSERT INTO triple.USER(USER_ID, NAME,  RGST_DTM, RGST_ID) VALUES(UUID(),'rebeca', NOW(),  '0');
INSERT INTO triple.USER(USER_ID, NAME,  RGST_DTM, RGST_ID) VALUES(UUID(),'tom', NOW(),  '0');
INSERT INTO triple.USER(USER_ID, NAME,  RGST_DTM, RGST_ID) VALUES(UUID(),'joy', NOW(),  '0');
INSERT INTO triple.USER(USER_ID, NAME,  RGST_DTM, RGST_ID) VALUES(UUID(),'irene', NOW(),  '0');
INSERT INTO triple.USER(USER_ID, NAME,  RGST_DTM, RGST_ID) VALUES(UUID(),'mia', NOW(),  '0');
INSERT INTO triple.USER(USER_ID, NAME,  RGST_DTM, RGST_ID) VALUES(UUID(),'july', NOW(),  '0');
INSERT INTO triple.USER(USER_ID, NAME,  RGST_DTM, RGST_ID) VALUES(UUID(),'karina', NOW(),  '0');
INSERT INTO triple.USER(USER_ID, NAME,  RGST_DTM, RGST_ID) VALUES(UUID(),'김민성', NOW(),  '0');
INSERT INTO triple.USER(USER_ID, NAME,  RGST_DTM, RGST_ID) VALUES(UUID(),'박재하', NOW(),  '0');
INSERT INTO triple.USER(USER_ID, NAME,  RGST_DTM, RGST_ID) VALUES(UUID(),'박창규', NOW(),  '0');
INSERT INTO triple.USER(USER_ID, NAME,  RGST_DTM, RGST_ID) VALUES(UUID(),'이아름', NOW(),  '0');
INSERT INTO triple.USER(USER_ID, NAME,  RGST_DTM, RGST_ID) VALUES(UUID(),'한아름', NOW(),  '0');
INSERT INTO triple.USER(USER_ID, NAME,  RGST_DTM, RGST_ID) VALUES(UUID(),'정바로', NOW(),  '0');
INSERT INTO triple.USER(USER_ID, NAME,  RGST_DTM, RGST_ID) VALUES(UUID(),'김제니', NOW(),  '0');
INSERT INTO triple.USER(USER_ID, NAME,  RGST_DTM, RGST_ID) VALUES(UUID(),'박하선', NOW(),  '0');
INSERT INTO triple.USER(USER_ID, NAME,  RGST_DTM, RGST_ID) VALUES(UUID(),'강동원', NOW(),  '0');
INSERT INTO triple.USER(USER_ID, NAME,  RGST_DTM, RGST_ID) VALUES(UUID(),'장동건', NOW(),  '0');
INSERT INTO triple.USER(USER_ID, NAME,  RGST_DTM, RGST_ID) VALUES(UUID(),'염정아', NOW(),  '0');
INSERT INTO triple.USER(USER_ID, NAME,  RGST_DTM, RGST_ID) VALUES(UUID(),'문근영', NOW(),  '0');
INSERT INTO triple.USER(USER_ID, NAME,  RGST_DTM, RGST_ID) VALUES(UUID(),'임수정', NOW(),  '0');
INSERT INTO triple.USER(USER_ID, NAME,  RGST_DTM, RGST_ID) VALUES(UUID(),'전지현', NOW(),  '0');
INSERT INTO triple.USER(USER_ID, NAME,  RGST_DTM, RGST_ID) VALUES(UUID(),'김윤석', NOW(),  '0');
INSERT INTO triple.USER(USER_ID, NAME,  RGST_DTM, RGST_ID) VALUES(UUID(),'김혜수', NOW(),  '0');
INSERT INTO triple.USER(USER_ID, NAME,  RGST_DTM, RGST_ID) VALUES(UUID(),'김수현', NOW(),  '0');
INSERT INTO triple.USER(USER_ID, NAME,  RGST_DTM, RGST_ID) VALUES(UUID(),'이정재', NOW(),  '0');
INSERT INTO triple.USER(USER_ID, NAME,  RGST_DTM, RGST_ID) VALUES(UUID(),'손석구', NOW(),  '0');
INSERT INTO triple.USER(USER_ID, NAME,  RGST_DTM, RGST_ID) VALUES(UUID(),'마동석', NOW(),  '0');
INSERT INTO triple.USER(USER_ID, NAME,  RGST_DTM, RGST_ID) VALUES(UUID(),'윤계상', NOW(),  '0');
INSERT INTO triple.USER(USER_ID, NAME,  RGST_DTM, RGST_ID) VALUES(UUID(),'장이수', NOW(),  '0');
INSERT INTO triple.USER(USER_ID, NAME,  RGST_DTM, RGST_ID) VALUES(UUID(),'송새벽', NOW(),  '0');
INSERT INTO triple.USER(USER_ID, NAME,  RGST_DTM, RGST_ID) VALUES(UUID(),'tomas', NOW(),  '0');
INSERT INTO triple.USER(USER_ID, NAME,  RGST_DTM, RGST_ID) VALUES(UUID(),'장근석', NOW(),  '0');
INSERT INTO triple.USER(USER_ID, NAME,  RGST_DTM, RGST_ID) VALUES(UUID(),'김재준', NOW(),  '0');
INSERT INTO triple.USER(USER_ID, NAME,  RGST_DTM, RGST_ID) VALUES(UUID(),'유병재', NOW(),  '0');
INSERT INTO triple.USER(USER_ID, NAME,  RGST_DTM, RGST_ID) VALUES(UUID(),'문상훈', NOW(),  '0');
INSERT INTO triple.USER(USER_ID, NAME,  RGST_DTM, RGST_ID) VALUES(UUID(),'김하늘', NOW(),  '0');
INSERT INTO triple.USER(USER_ID, NAME,  RGST_DTM, RGST_ID) VALUES(UUID(),'박서준', NOW(),  '0');
INSERT INTO triple.USER(USER_ID, NAME,  RGST_DTM, RGST_ID) VALUES(UUID(),'최우식', NOW(),  '0');
INSERT INTO triple.USER(USER_ID, NAME,  RGST_DTM, RGST_ID) VALUES(UUID(),'김태형', NOW(),  '0');
INSERT INTO triple.USER(USER_ID, NAME,  RGST_DTM, RGST_ID) VALUES(UUID(),'미노이', NOW(),  '0');
INSERT INTO triple.USER(USER_ID, NAME,  RGST_DTM, RGST_ID) VALUES(UUID(),'이용진', NOW(),  '0');
INSERT INTO triple.USER(USER_ID, NAME,  RGST_DTM, RGST_ID) VALUES(UUID(),'이진호', NOW(),  '0');
INSERT INTO triple.USER(USER_ID, NAME,  RGST_DTM, RGST_ID) VALUES(UUID(),'장나라', NOW(),  '0');
INSERT INTO triple.USER(USER_ID, NAME,  RGST_DTM, RGST_ID) VALUES(UUID(),'윤미나', NOW(),  '0');
INSERT INTO triple.USER(USER_ID, NAME,  RGST_DTM, RGST_ID) VALUES(UUID(),'김고은', NOW(),  '0');
INSERT INTO triple.USER(USER_ID, NAME,  RGST_DTM, RGST_ID) VALUES(UUID(),'이민기', NOW(),  '0');
INSERT INTO triple.USER(USER_ID, NAME,  RGST_DTM, RGST_ID) VALUES(UUID(),'서현진', NOW(),  '0');
INSERT INTO triple.USER(USER_ID, NAME,  RGST_DTM, RGST_ID) VALUES(UUID(),'이병헌', NOW(),  '0');
INSERT INTO triple.USER(USER_ID, NAME,  RGST_DTM, RGST_ID) VALUES(UUID(),'정유미', NOW(),  '0');


/* 유저별 포인트 현황 셋팅 */ 
INSERT INTO triple.POINT (POINT_ID,USER_ID,VALUE,RGST_DTM,RGST_ID)
SELECT
	UUID()
    ,USER_ID 
    ,0
    ,NOW()
    ,USER_ID
    FROM triple.USER;

/* CODE 테이블 인서트 */
INSERT INTO triple.CODE(CODE_VALUE, CODE_DESC, RGST_DTM, RGST_ID) VALUES('PLUS','획득',NOW(), 0);
INSERT INTO triple.CODE(CODE_VALUE, CODE_DESC, RGST_DTM, RGST_ID) VALUES('MINUS','회수',NOW(), 0);
INSERT INTO triple.CODE(CODE_VALUE, CODE_DESC, RGST_DTM, RGST_ID) VALUES('CONTENT_TEXT','1자 이상 텍스트 작성',NOW(), 0);
INSERT INTO triple.CODE(CODE_VALUE, CODE_DESC, RGST_DTM, RGST_ID) VALUES('CONTENT_PHOTO','1장 이상 사진 첨부',NOW(), 0);
INSERT INTO triple.CODE(CODE_VALUE, CODE_DESC, RGST_DTM, RGST_ID) VALUES('BONUS_FIRST','특정 장소에 첫 리뷰 작성',NOW(), 0);


/* PLACE 테이블 인서트 */
INSERT INTO triple.PLACE(PLACE_ID, NAME, RGST_DTM, RGST_ID) VALUES(UUID(), '신라스테이',NOW(), 0);
INSERT INTO triple.PLACE(PLACE_ID, NAME, RGST_DTM, RGST_ID) VALUES(UUID(), '명래 민박',NOW(), 0);
INSERT INTO triple.PLACE(PLACE_ID, NAME, RGST_DTM, RGST_ID) VALUES(UUID(), '하루 한옥',NOW(), 0);
INSERT INTO triple.PLACE(PLACE_ID, NAME, RGST_DTM, RGST_ID) VALUES(UUID(), '신라호텔',NOW(), 0);
INSERT INTO triple.PLACE(PLACE_ID, NAME, RGST_DTM, RGST_ID) VALUES(UUID(), '파라스파라서울',NOW(), 0);
INSERT INTO triple.PLACE(PLACE_ID, NAME, RGST_DTM, RGST_ID) VALUES(UUID(), '조선호텔 제주',NOW(), 0);
INSERT INTO triple.PLACE(PLACE_ID, NAME, RGST_DTM, RGST_ID) VALUES(UUID(), '호텔 마리나베이',NOW(), 0);
INSERT INTO triple.PLACE(PLACE_ID, NAME, RGST_DTM, RGST_ID) VALUES(UUID(), '롯데 시그니엘 서울',NOW(), 0);
INSERT INTO triple.PLACE(PLACE_ID, NAME, RGST_DTM, RGST_ID) VALUES(UUID(), '그랜드 머큐어 앰배서더 호텔',NOW(), 0);
INSERT INTO triple.PLACE(PLACE_ID, NAME, RGST_DTM, RGST_ID) VALUES(UUID(), '그랜드 하얏트 서울',NOW(), 0);
INSERT INTO triple.PLACE(PLACE_ID, NAME, RGST_DTM, RGST_ID) VALUES(UUID(), '콘래드 서울',NOW(), 0);
INSERT INTO triple.PLACE(PLACE_ID, NAME, RGST_DTM, RGST_ID) VALUES(UUID(), '웨스틴 조선 서울 호텔',NOW(), 0);
INSERT INTO triple.PLACE(PLACE_ID, NAME, RGST_DTM, RGST_ID) VALUES(UUID(), '포시즌스 호텔 서울',NOW(), 0);
INSERT INTO triple.PLACE(PLACE_ID, NAME, RGST_DTM, RGST_ID) VALUES(UUID(), '노보텔 앰배서더 용산',NOW(), 0);
INSERT INTO triple.PLACE(PLACE_ID, NAME, RGST_DTM, RGST_ID) VALUES(UUID(), '인천 파라다이스 시티',NOW(), 0);


/* REWARD 테이블 인서트 */ 
INSERT INTO triple.REWARD(ACTION, TYPE, VALUE, USE_YN, RGST_DTM, RGST_ID) VALUES ("PLUS", "CONTENT_TEXT", 1, "Y", NOW(), "ADMIN");
INSERT INTO triple.REWARD(ACTION, TYPE, VALUE, USE_YN, RGST_DTM, RGST_ID) VALUES ("PLUS", "CONTENT_PHOTO", 1, "Y", NOW(), "ADMIN");
INSERT INTO triple.REWARD(ACTION, TYPE, VALUE, USE_YN, RGST_DTM, RGST_ID) VALUES ("PLUS", "BONUS_FIRST", 1, "Y", NOW(), "ADMIN");

commit;




